/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.cautiousExplorerActors;

import it.unibo.supports2021.IssWsHttpJavaSupport;

public class App {

    public static void main(String[] args) {

        System.out.println("Avvio Cautious Explorer:");

        RobotActorController rac = new RobotActorController("cautiosDemo");

        IssWsHttpJavaSupport support = IssWsHttpJavaSupport.createForWs("localhost:8091" );

        support.registerActor(rac);

        rac.send("startApp");

    }
}
